// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIWBWSwxMA7ZEeYFJifxM_e2NiQzRafA',
    appId: '1:490854661850:web:00c4390848cde19e5cafe3',
    messagingSenderId: '490854661850',
    projectId: 'country-game-91d59',
    authDomain: 'country-game-91d59.firebaseapp.com',
    storageBucket: 'country-game-91d59.appspot.com',
    measurementId: 'G-PM82ZPF3K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UM1QVtW6xM9YB2r93KMsVpNzx532HeI',
    appId: '1:490854661850:android:163fb0fb97d542615cafe3',
    messagingSenderId: '490854661850',
    projectId: 'country-game-91d59',
    storageBucket: 'country-game-91d59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3OtXOxBe5JjrENM2Nlp8nT0FO3vqw2y0',
    appId: '1:490854661850:ios:a038959fffd261ed5cafe3',
    messagingSenderId: '490854661850',
    projectId: 'country-game-91d59',
    storageBucket: 'country-game-91d59.appspot.com',
    iosBundleId: 'com.example.countryGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3OtXOxBe5JjrENM2Nlp8nT0FO3vqw2y0',
    appId: '1:490854661850:ios:a038959fffd261ed5cafe3',
    messagingSenderId: '490854661850',
    projectId: 'country-game-91d59',
    storageBucket: 'country-game-91d59.appspot.com',
    iosBundleId: 'com.example.countryGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeIWBWSwxMA7ZEeYFJifxM_e2NiQzRafA',
    appId: '1:490854661850:web:e9d9780f3ee2dd5a5cafe3',
    messagingSenderId: '490854661850',
    projectId: 'country-game-91d59',
    authDomain: 'country-game-91d59.firebaseapp.com',
    storageBucket: 'country-game-91d59.appspot.com',
    measurementId: 'G-Q734MBHJLL',
  );
}
